version: '3.7'

services:
  my-ubuntu-container:
    container_name: my-ubuntu-container
    build:
      context: .
      dockerfile: Dockerfile
    command: sleep infinity
    volumes:
      - ./data:/home/jenai/data
      - /var/run/docker.sock:/var/run/docker.sock
    # Optional: Wenn Sie Docker-Befehle direkt beim Start ausführen möchten, ersetzen Sie 'sleep infinity' durch Ihren Befehl.
